id: ProjectTable
header: Projects
fields:
    - id: id
      title: Id
      cellType: id
    - id: key
      title: Key
      cellType: text
      flex: 1
    - id: name
      title: Name
      cellType: text
      flex: 2
    - id: color
      title: Color
      cellType: text
      flex: 1
    - id: _modifiedDate
      title: Modified
      cellType: timeAgo
      flex: 1
rowActions:
    - id: edit
      iconName: Edit
      title: Edit
    - id: delete
      iconName: Delete
      title: Delete
tableActions:
    - id: back
      iconName: arrow_upward
      title: Go back
    - id: new
      iconName: add
      title: New item
