export const itemStructure = `export type IPerson = {
    id: string;
    key: string;
    firstName: string;
    lastName: string;
    shortDescription: string;
    dateOfBirth?: string;
    imageUrl?: string;
    thumbUrl?: string;
    socialTwitterUrl?: string;
    socialFacebookUrl?: string;
    socialInstagramUrl?: string;
    socialLinkedInUrl?: string;
    pinterestUrl?: string;
    wikipediaUrl?: string;
    website?: string;
    phoneNumber?: string;
    images?: string[];
    email?: string;
    notes?: string;
    height?: number;
    netWorth?: number;
    company?: string;
    jobTitle?: string;
    tags: string[];
    dataTags: string[];
    tier?: number;
    gender?: string;
    category: string;
};
`;
